title: MIDAFY's Blog
author: MIDAFY # 이 속성이 없으면 푸터 연락처 영역에 블로그 제목이 한 번 더 나옵니다!
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: ji7163

# Build settings
theme: minima
plugins:
  - jekyll-feed
future: true
timezone: "Asia/Seoul"

header_pages:
  - intro.md
  - posts.md
